name: Pester tests
on: push

jobs:
  pester-tests:
    name: Pester tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        shell: pwsh
        run: |
          Install-Module -Name EZLog -Force
      - name: Perform Pester tests
        shell: pwsh
        run: |
          Invoke-Pester
